      - name: Start API (background)
        shell: bash
        run: |
          set -e
          export PORT=3001

          if [ -f server/index.ts ]; then
            PORT=$PORT npx tsx server/index.ts > api.log 2>&1 &
          elif [ -f server/app.ts ]; then
            PORT=$PORT npx tsx server/app.ts > api.log 2>&1 &
          elif [ -f server/main.ts ]; then
            PORT=$PORT npx tsx server/main.ts > api.log 2>&1 &
          elif npm run | grep -q '^  dev:server'; then
            PORT=$PORT npm run dev:server > api.log 2>&1 &
          else
            PORT=$PORT npm run dev > api.log 2>&1 &
          fi

          echo $! > api.pid
